Parameters:
  BootstrapVersion:
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
    Type: AWS::SSM::Parameter::Value<String>
Resources:
  CDKMetadata:
    Metadata:
      aws:cdk:path: Szakdolgozat/CDKMetadata/Default
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzPTM1RMLC/WTU7J1s3JTNKrDi5JTM7WAQrFpyYX6VUHpRbkF2eW5BdV6jin5SF4tRBucX5pUXJqrU5AZUlGfp6+sZ6hoZ6BYlZxZqZuUWleSWZuql4QhAYA3cPEW2wAAAA=
    Type: AWS::CDK::Metadata
  Szakdolgozat7E3C5AC1:
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Szakdolgozat/Szakdolgozat/Resource
    Properties:
      RepositoryName: base
    Type: AWS::ECR::Repository
    UpdateReplacePolicy: Retain
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert: !Not
          - !Contains
            - - '1'
              - '2'
              - '3'
              - '4'
              - '5'
            - !Ref 'BootstrapVersion'
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
